https://docusaurus.io/
https://docusaurus.io/docs/create-doc
https://www.mkdocs.org/user-guide/writing-your-docs/
https://squidfunk.github.io/mkdocs-material/
https://docs.hektorprofe.net/python/documentacion-y-pruebas/pydoc/
https://www.datacamp.com/tutorial/docstrings-python
https://www.dataquest.io/blog/documenting-in-python-with-docstrings/
https://www.programiz.com/python-programming/docstrings
https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats
https://realpython.com/documenting-python-code/#basics-of-commenting-code
https://github.com/reconquest/shdoc#name
https://stackedit.io/app#validate
https://dillinger.io/
