https://cs50.harvard.edu/web/2020/projects/0/search/
file:///home/daniel/tron/biblioteca/CURSOS/CursoHarvardWeb/clase0-HTML-CSS/practicas/responsive.html
https://learning.edx.org/course/course-v1:HarvardX+CS50W+Web/home
https://www.google.com/search?q=dise%C3%B1o+de+menu+responsive+sencillo+f%C3%A1cil+con+bootstrap+5&sxsrf=AJOqlzW788RndtU-neSVT8Bqo0l2kgYyFg%3A1676143383011&ei=F-vnY5gHnaHk2g_Bo6rQCg&ved=0ahUKEwjY7r7XmI79AhWdEFkFHcGRCqoQ4dUDCA8&uact=5&oq=dise%C3%B1o+de+menu+responsive+sencillo+f%C3%A1cil+con+bootstrap+5&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAE6BAgjECc6BQgAEJECOgUIABCABDoFCC4QgAQ6DgguEIAEEMcBENEDENQCOgQIABBDOggILhCABBDUAjoKCAAQgAQQFBCHAjoHCC4Q1AIQQzoICAAQgAQQywE6CggAEIAEEAoQywE6CQgAEBYQHhDxBDoLCCEQFhAeEPEEEB06CgghEBYQHhAPEB06CAghEBYQHhAdOgcIIRCgARAKOgQIIRAKOgUIABCiBEoECEEYAEoECEYYAFAAWOTmAWCA7AFoA3ABeACAAcYCiAHARJIBCDAuNDguNC4xmAEAoAEBwAEB&sclient=gws-wiz-serp
https://www.youtube.com/watch?v=lcUWpoAKUYk
https://www.youtube.com/watch?v=jOKbQRp-eek
https://www.youtube.com/watch?v=F55FC7UheLA
https://programarfacil.com/blog/crear-una-web-responsive-con-bootstrap/
http://www.falconmasters.com/web-design/menu-de-navegacion-responsive/
http://www.falconmasters.com/web-design/menu-desplegable-adaptable-dispositivos-moviles/
https://getbootstrap.esdocu.com/docs/5.1/examples/
https://www.creativosonline.org/menu-html-css.html
https://getbootstrap.esdocu.com/docs/5.1/components/navbar/
https://getbootstrap.com/
https://getbootstrap.com/docs/5.3/getting-started/introduction/
https://getbootstrap.com/docs/5.3/examples/
https://themes.getbootstrap.com/
https://blog.getbootstrap.com/
