https://wiki.archlinux.org/title/MPRIS
https://unix.stackexchange.com/questions/437735/prevent-system-from-going-to-sleep-suspend-how-xviewer-vlc-do-it
https://dbus.freedesktop.org/doc/dbus-monitor.1.html
https://wiki.videolan.org/DBus-usage/
http://svictor.net/tools/linux-co/257-control-vlc-through-dbus-for-shortcuts-etc
https://specifications.freedesktop.org/mpris-spec/latest/interfaces.html
https://specifications.freedesktop.org/mpris-spec/latest/fullindex.html
https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html
https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html
https://specifications.freedesktop.org/mpris-spec/latest/Playlists_Interface.html
