https://www.mkdocs.org/dev-guide/themes/#supporting-theme-localizationtranslation
https://squidfunk.github.io/mkdocs-material/creating-your-site/#building-your-site
https://docs.hektorprofe.net/python/documentacion-y-pruebas/pydoc/
https://www.dataquest.io/blog/documenting-in-python-with-docstrings/
https://www.programiz.com/python-programming/docstrings
https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats
https://realpython.com/documenting-python-code/#basics-of-commenting-code
https://www.manpagez.com/man/1/pydoc/
https://docs.python.org/es/dev/library/pydoc.html
https://www.npmjs.com/package/markserv#stopwatch-just-in-time-templating
chrome://extensions/?id=jnihajbhpnppcggbcgedagnkighmdlei
chrome://newtab/
https://github.com/reconquest/shdoc/blob/master/examples/readme-example.sh
https://github.com/reconquest/shdoc/blob/master/examples/readme-example.md#validate
https://www.google.com/search?q=traductor&oq=traductor&aqs=chrome.0.69i59l3j69i61j69i65j69i61j69i65j69i61.4305j0j1&sourceid=chrome&ie=UTF-8
http://localhost:8642/Leeme.md
https://github.com/juanelas/markdown-to-standalone-html
https://github.com/asottile/markdown-code-blocks
https://www.google.com/search?q=traducir+al+ingles&oq=traducir+al+ingles&aqs=chrome.0.69i59l2j35i39j0i512l3j0i10i512j0i512l3.4809j0j1&sourceid=chrome&ie=UTF-8
