https://www.google.com/search?q=bash+script%3A+how+run+a+bash+env+python+enviroment+in+a+bash+scipt&oq=bash+script%3A+how+run+a+bash+env+python+enviroment+in+a+bash+scipt&aqs=chrome..69i57.82202j1j1&sourceid=chrome&ie=UTF-8
https://stackoverflow.com/questions/13122137/how-to-source-virtualenv-activate-in-a-bash-script
https://stackoverflow.com/questions/61906957/how-to-activate-a-python-virtualenv-using-a-bash-script-and-keep-it-after-the-sc
https://stackoverflow.com/questions/73551877/how-to-run-shell-exectued-python-script-in-a-virtual-environment
https://stackoverflow.com/questions/71682064/running-a-python-environment-and-python-code-in-that-env-from-a-bash-shell-scrip
https://stackoverflow.com/questions/42257321/bash-script-to-run-python-script-in-virtualenv
https://codingnomads.co/blog/python-environment-variables-set-a-variable-in-bash/
https://www.infoworld.com/article/3239675/virtualenv-and-venv-python-virtual-environments-explained.html
https://superuser.com/questions/1547228/how-to-activate-python-virtualenv-through-shell-script
https://opensource.com/article/20/1/setv-bash-function
https://askubuntu.com/questions/1164621/bash-script-to-source-a-python-virtual-environment
https://askubuntu.com/questions/813929/how-to-activate-a-virtualenv-within-bash-script-resulting-in-activated-prompt
https://askubuntu.com/questions/965475/cannot-activate-virtual-environment-with-a-shell-script
https://askubuntu.com/questions/1131539/make-virtualenv-and-activate-it-with-shell-script
https://arshovon.com/blog/python-background/
http://localhost:8642/Leeme.md
http://localhost:8642/Leeme.md
https://www.google.com/search?q=bash+%22%26%22+%22bg%22+command&oq=bash+%22%26%22+%22bg%22+command+&aqs=chrome..69i57j0i22i30j0i22i30i625j0i22i30.133218j1j1&sourceid=chrome&ie=UTF-8
https://www.cyberciti.biz/faq/unix-linux-bg-command-examples-usage-syntax/
https://www.bonaval.com/kb/sistemas-operativos/linux-sistemas-operativos/manejar-procesos-en-linux-en-terminal-comandos-bg-y-fg-background-y-foreground
https://www.geeksforgeeks.org/bg-command-in-linux-with-examples/
https://pimylifeup.com/bg-command-linux/
https://www.linuxfordevices.com/tutorials/linux/bg-command-in-linux
https://www.google.com/search?q=bash+how+to+redirect+stderr+to+%2Fdev%2Fnull&sxsrf=AJOqlzVvC6eBp-XEmK1nAQF5AhUki5szzw%3A1677249929889&ei=ic34Y4ryNar8wbkP3OesKA&oq=bash+how+redirec&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAxgAMgYIABAWEB4yCQgAEBYQHhDxBDIJCAAQFhAeEPEEMgkIABAWEB4Q8QQyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIJCAAQFhAeEPEEMgYIABAWEB46BwgjEOoCECc6DQguEMcBENEDEOoCECc6DQgAEI8BEOoCELQCGAE6DQguEI8BEOoCELQCGAE6BAgjECc6BAgAEEM6EQguEIAEELEDEIMBEMcBENEDOgsIABCABBCxAxCDAToECC4QQzoLCC4QsQMQgwEQ1AI6CwguEIAEELEDEIMBOgsILhCDARCxAxCABDoICAAQgAQQywE6CggAEIAEEBQQhwJKBAhBGABQsgxYnipg7ERoAXABeAGAAcQDiAHiF5IBCjAuMTQuMS4wLjGYAQCgAQGwARTAAQHaAQYIARABGAo&sclient=gws-wiz-serp
http://localhost:8642/Leeme.md
https://unix.stackexchange.com/questions/706756/how-can-i-open-multiple-files-with-xdg-open
https://www.google.com/search?q=how+read+lines+in+a+file+bash+whitch+for+loop&oq=how+read+lines+in+a+file+bash+whitch+for+loop&aqs=chrome..69i57j33i10i160l2.54329j0j7&sourceid=chrome&ie=UTF-8
https://stackoverflow.com/questions/1521462/looping-through-the-content-of-a-file-in-bash
https://stackoverflow.com/questions/19058404/reading-files-line-by-line-in-by-using-for-loop-bash-script
http://localhost:8642/Leeme.md
