https://www.mkdocs.org/dev-guide/themes/#supporting-theme-localizationtranslation
https://squidfunk.github.io/mkdocs-material/creating-your-site/#building-your-site
https://docs.hektorprofe.net/python/documentacion-y-pruebas/pydoc/
https://www.dataquest.io/blog/documenting-in-python-with-docstrings/
https://www.programiz.com/python-programming/docstrings
https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats
https://realpython.com/documenting-python-code/#basics-of-commenting-code
https://github.com/reconquest/shdoc#name
https://stackedit.io/app#
https://dillinger.io/
https://www.google.com/search?q=man+pydoc+arch&sxsrf=AJOqlzWguGmy4wJ0Y4FVH1iOVXNefziN4Q%3A1676755386267&ei=ukHxY-qCEOyrwbkP56KhiA4&ved=0ahUKEwjqx7HJgKD9AhXsVTABHWdRCOEQ4dUDCA8&uact=5&oq=man+pydoc+arch&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCCEQoAEyBQghEKABOgcIABAeELADOgkIABAIEB4QsAM6BggAEBYQHjoECCEQFUoECEEYAVD_BVi_FWCsHGgBcAB4AIABrwGIAa0GkgEDMC41mAEAoAEByAECwAEB&sclient=gws-wiz-serp
https://www.manpagez.com/man/1/pydoc/
https://docs.python.org/es/dev/library/pydoc.html
https://www.google.com/search?q=where+store+pydoc+the+html+files&sxsrf=AJOqlzXiFOrh3PDnsSVsT3geqi3xdyterA%3A1676766379439&ei=q2zxY8-dF7j7wbkPjbOjyAQ&ved=0ahUKEwiPn6jDqaD9AhW4fTABHY3ZCEkQ4dUDCA8&uact=5&oq=where+store+pydoc+the+html+files&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIICCEQoAEQwwQ6CggAEEcQ1gQQsAM6CgghEKABEMMEEAo6BQgAEKIESgQIQRgAUKlEWPhdYPFhaAJwAXgAgAHMAYgBgAySAQUwLjguMZgBAKABAcgBCMABAQ&sclient=gws-wiz-serp
https://subscription.packtpub.com/book/application-development/9781783280971/18/ch18lvl1sec164/using-pydoc-for-documentation
https://bytes.com/topic/python/answers/41060-how-can-i-use-pydoc-generate-html-file-modul-directory-d
https://prosperocoder.com/posts/python/pydoc-html-reports/
https://www.lawebdelprogramador.com/foros/Python/709159-pydoc.html
https://docs.python.org/es/dev/library/pydoc.html
https://martinber.github.io/guia-sphinx/alternativas/pydoc.html
http://mundogeek.net/archivos/2008/07/07/documentacion-en-python/
https://python-para-impacientes.blogspot.com/2014/02/docstrings.html
https://stackoverflow.com/questions/44782238/how-to-use-pydoc-to-generate-an-html-page
https://stackoverflow.com/questions/27579778/producing-a-single-html-help-page-for-a-module-function-class-similar-to-r
https://stackoverflow.com/questions/57135776/what-does-w-do-in-pydoc-and-can-it-generate-doc-output
