https://www.google.com/search?q=tvn+studio+dragon&oq=tvn+studio+dragon&aqs=chrome..69i57.8649j0j4&sourceid=chrome&ie=UTF-8
https://www.mkdocs.org/user-guide/installation/
https://github.com/markserv/markserv#readme
https://docs.hektorprofe.net/python/documentacion-y-pruebas/pydoc/
https://docs.python.org/es/dev/library/pydoc.html
https://realpython.com/documenting-python-code/#basics-of-commenting-code
https://squidfunk.github.io/mkdocs-material/creating-your-site/#building-your-site
https://github.com/AndCake/micro-plugin-lsp
https://docs.github.com/es/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists
https://github.com/juanelas/markdown-to-standalone-html
https://github.com/topics/pdf-search
https://github.com/topics/pdf-search-engine
https://github.com/oisincoveney/PDF-Search-Engine-C-
https://github.com/lebebr01/pdfsearch
https://github.com/alexcg1/example-pdf-search/
https://github.com/peterwilliams97/pdf-search
https://github.com/PaperCutSoftware/pdfsearch
https://github.com/cran/pdfsearch
https://github.com/topics/document-search
https://github.com/PDFTron/pdftron-document-search
https://github.com/topics/pdf?l=html
https://github.com/topics/pdf-search?l=python
https://github.com/topics/pdf-search-engine?l=python
https://github.com/edoardottt/multi-pdf-finder
https://github.com/ElectricRCAircraftGuy/PDF2SearchablePDF
